### ISSUE TITLE
Salut

### ISSUE THREAD

**Issue by LookBehindYou44** [tutyamxx/AMXX_Codes#1]
Salut , oare ai mai facut ceva progrese cu Mario COin? Am vazut ca o fost dezaprobat da e o idee super misto , doar trebe rezolvat sa nu mai treaga gloantele prin adversari :) Daca crezi ca este vreo sansa sa i faci un update ar fi super :D numa zic nu am nicio pretentie , imi place mult munca ta.

**Comment by tutyamxx** [comment]
Salut, nu ma mai ocup de vreo 8 ani :) sorry -.-
